services:
  chroma:
    image: chromadb/chroma
    volumes:
      - ./chroma/:/chroma/chroma/
    # ports:
    #   - 1234:8000

  api:
    build: ./api
    ports:
      - 8000:8000
    env_file:
      - ./api/.env
    depends_on:
      chroma:
        condition: service_started

# docker compose up -d
